import Head from 'next/head'

import Hero from '../components/inicio/Hero'
import Developer from '../components/inicio/Developer'
import Designer from '../components/inicio/Designer'
import QuienSoy from '../components/inicio/QuienSoy'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      
      <Hero />
      <Developer />
      <Designer />
      <QuienSoy />
    </>
  )
}
